#!/usr/bin/env bash

for path in $(dirname $0)/*; do
    name=$(basename "${path}")
    if [[ "${name}" != "INSTALL" ]]; then
        if [[ -d "${path}" && ! -L "${path}" ]]; then
            rm -rf "${HOME}/.${name}"
        fi

        chmod -R go-rwx "${path}"
        ln -sf "${PWD}/${path}" "${HOME}/.${name}"
    fi
done

# Install Vim Vundle
git clone https://github.com/VundleVim/Vundle.Vim ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
