# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# format = """\
# [](bg:#030B16 fg:#7DF9AA)\
# [󰀵 ](bg:#7DF9AA fg:#090c0c)\
# [](fg:#7DF9AA bg:#1C3A5E)\
# $time\
# [](fg:#1C3A5E bg:#3B76F0)\
# $directory\
# [](fg:#3B76F0 bg:#FCF392)\
# $git_branch\
# $git_status\
# $git_metrics\
# [](fg:#FCF392 bg:#030B16)\
# $character\
# """

right_format = '$time'

add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = false
# format = '[$path ](bold yellow)'
# style = 'fg:#E4E4E4 bg:#3B76F0'
style = '#00AFFF'
before_repo_root_style = '#00AFFF dimmed'
repo_root_style = 'bold #00AFFF'

[git_branch]
# format = '[$symbol$branch(:$remote_branch) ](green)'
format = '[$symbol$branch(:$remote_branch)](bright-green) '
# symbol = ' '
# style = 'fg:#1C3A5E bg:#FCF392'

[git_status]
# format = '[$all_status ]($style)'
conflicted = '=$count'
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '?$count'
stashed = '$$count'
modified = '!$count'
staged = '+$count'
renamed = '»$count'
deleted = '✘$count'
# style = 'fg:#1C3A5E bg:#FCF392'

[cmd_duration]
disabled = true

[line_break]
disabled = true

[time]
disabled = false
# format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
# time_format = '%R' # Hour:Minute Format
# style = 'bg:#1d2230'
