# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# format = """\
# [](bg:#030B16 fg:#7DF9AA)\
# [󰀵 ](bg:#7DF9AA fg:#090c0c)\
# [](fg:#7DF9AA bg:#1C3A5E)\
# $time\
# [](fg:#1C3A5E bg:#3B76F0)\
# $directory\
# [](fg:#3B76F0 bg:#FCF392)\
# $git_branch\
# $git_status\
# $git_metrics\
# [](fg:#FCF392 bg:#030B16)\
# $character\
# """

# right_format = '$time'

add_newline = false

# Simulate Powerlevel10k with lean prompt style
#
# Wizard options:
#   nerdfont-complete + powerline, small icons, unicode, lean, 1 line,
#   compact, few icons, concise, instant_prompt=verbose.
#
# Tip: one-liner to print colormap.
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bold 39'
before_repo_root_style = '31'
repo_root_style = 'bold 39'

[git_branch]
format = '[$symbol$branch(:$remote_branch)](green)'
symbol = ''
# symbol = ' '

[git_status]
format = '([$all_status$ahead_behind]($style)) '
conflicted = ' [~$count](196)'
ahead = ' ⇡$count'
behind = ' ⇣$count'
diverged = ' ⇕⇡$ahead_count⇣$behind_count'
untracked = ' [?$count](39)'
stashed = ' \$$count'
modified = ' [!$count](178)'
staged = ' +$count'
renamed = ' »$count'
deleted = ' ✘$count'
style = '76'

[cmd_duration]
disabled = true

[line_break]
disabled = true

# [time]
# disabled = false
# format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
# time_format = '%R' # Hour:Minute Format
# style = 'bg:#1d2230'

[aws]
# symbol = '󰸏 '
# symbol = ' '
symbol = 'aws '

[gcloud]
# symbol = '󱇶 '
symbol = 'gcp '
detect_env_vars = ['GCP_PROJECT_ID']
